### ISSUE TITLE
error trying to compile to generic linux

### ISSUE THREAD

**Issue by joaoantoniocardoso** [enGits/engrid#63]
Hi, I was trying to compile following the [[enGrid 1.4] Installation - Building enGrid on a Generic Linux System](https://github.com/enGits/engrid/wiki/%5BenGrid-1.4%5D-Installation#Other_Compatible_Linux_Distributions) and `scripts/build-nglib.sh` failed because ` http://engits.eu/files/netgen-4.9.13.zip` doesn't exist:

> ./build-nglib.sh: line 27: cd: netgen_svn: No such file or directory
--2017-06-19 19:11:06--  http://engits.eu/files/netgen-4.9.13.zip
Resolving engits.eu... 178.238.231.152
Connecting to engits.eu|178.238.231.152|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-06-19 19:11:08 ERROR 404: Not Found.

I also notice that the script doesn't verifies if the file was downloaded and simple tries to extract it.

How could i fix it? Thanks.

**Comment by ftpronk** [comment]
Version 1.4 is no longer supported.  Pull the new code from the master branch.
A fix was nonetheless pushed to the branch release-1.4.  See commit  0d4f4e9  and issue #62.

**Comment by RGD2** [comment]
... This is marked closed.. yet this is still broken (as of this time) in master **AND** release-1.4

Steps to reproduce: 

On a fresh ubuntu image, clone rep. `./build.bash ubuntu`

breaks.

```
git checkout -- src/scripts/qmake
git checkout release-1.4
./build.bash ubuntu
```

Still broken.

I'm giving up on engrid for now -- too hard to get onto xenial / horrifically broken build instructions for new users.

Seriously, what is up with the number of projects whose dev's never seem to care that newcomers can't successfully follow their build tutorial on some recent LTS linux system?

Document your damn toolchain setup steps! 
I don't care that it's scripted, I just care that the 'howto' page has a 'sudo apt install blah blah blah' line that works under some recent LTS debian / ubuntu. 

You can't regression test that without also occasionally doing the setup 'from scratch' yourself from time to time. If you dismissively close 'warning sign' issue tickets like this, yet others come along and find them still broken -- we're all just going elsewhere.

Why don't you just dockerise the build platform? That works too. Hell, I'm running OpenFOAM in a built docker as app -- a joy to get runnig, It would have been nice if engrid itself runs in a docker or it's [appImage](https://appimage.org/).

I bet it's 'fixed for you' because you've got some bespoke hand-tuned linux setup you're developing in, but if ordinary incoming dev's can't reproduce that, your project is broken.

Bye!

**Comment by ftpronk** [comment]
The older releases of enGrid are no longer supported. The instructions have not been updated due to time == money constraints, but the master branch is used regularly and should work on current Linux/Mac systems.

The new/development release of enGrid should be compiled using the CMake build system. For ease-of-use, the ccmake front end is recommanded.

First-time Xenial compilation was successful this morning, without changes.  Follow CMake cues for missing dependencies.

Kind regards.
